services:
  Runway\Model\Provider\IDataStoragePropertiesProvider:
    class: Runway\Model\Provider\DataStoragePropertiesProvider

  Runway\Model\Helper\IDataStoragePropertiesHelper:
    class: Runway\Model\Helper\DataStoragePropertiesHelper

  Runway\Model\Converter\IDataStoragePropertyBuilder:
    class: Runway\Model\Converter\DataStoragePropertyBuilder

  Runway\Model\Converter\IDataStoragePropertiesConverter:
    class: Runway\Model\Converter\DataStoragePropertiesConverter

  Runway\Model\DataBuilder\IDataStoragePropertyBuilder:
    class: Runway\Model\DataBuilder\DataStoragePropertyBuilder